#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hashie
Version  : 3.4.2
Release  : 6
URL      : https://rubygems.org/downloads/hashie-3.4.2.gem
Source0  : https://rubygems.org/downloads/hashie-3.4.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coderay
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-i18n
BuildRequires : rubygem-method_source
BuildRequires : rubygem-minitest
BuildRequires : rubygem-pry
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-slop
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
# Hashie
[![Join the chat at https://gitter.im/intridea/hashie](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/intridea/hashie?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hashie-3.4.2
gem spec %{SOURCE0} -l --ruby > rubygem-hashie.gemspec

%build
gem build rubygem-hashie.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hashie-3.4.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hashie-3.4.2
rspec -Ilib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/hashie-3.4.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Clash/ChainError/cdesc-ChainError.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Clash/_end%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Clash/_parent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Clash/cdesc-Clash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Clash/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/CoercionError/cdesc-CoercionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/_regular_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/_regular_writer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/assert_property_exists%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/assert_property_required%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/assert_property_set%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/assert_required_attributes_set%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/cdesc-Dash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/defaults-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/fail_no_property_error%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/fail_property_required_error%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/inherited-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/initialize_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/properties-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/property%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/property-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/required%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/required%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/required_properties-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Dash/update_attributes%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/coerce_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/coerce_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/coerce_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/inherited-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/key_coercion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/key_coercions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/lenient_value_coercions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/strict_value_coercions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/ClassMethods/value_coercion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/InstanceMethods/cdesc-InstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/InstanceMethods/coerce_or_init-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/InstanceMethods/custom_writer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/InstanceMethods/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/InstanceMethods/set_value_with_coercion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/cdesc-Coercion.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Coercion/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/IndifferentAccess/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/IndifferentAccess/ClassMethods/property%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/IndifferentAccess/ClassMethods/transformation_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/IndifferentAccess/ClassMethods/transformed_property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/IndifferentAccess/ClassMethods/translation_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/IndifferentAccess/cdesc-IndifferentAccess.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/IndifferentAccess/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/inherited-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/inverse_translations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/permitted_input_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/transformation_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/transformed_property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/transforms-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/translation_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/translations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/ClassMethods/translations_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/InstanceMethods/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/InstanceMethods/cdesc-InstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/InstanceMethods/initialize_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/InstanceMethods/property_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/cdesc-PropertyTranslation.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/PropertyTranslation/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Dash/cdesc-Dash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFetch/UndefinedPathError/cdesc-UndefinedPathError.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFetch/cdesc-DeepFetch.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFetch/deep_fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFind/_deep_find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFind/_deep_find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFind/cdesc-DeepFind.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFind/deep_detect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFind/deep_find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFind/deep_find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepFind/deep_select-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepLocate/_deep_locate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepLocate/cdesc-DeepLocate.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepLocate/deep_locate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepLocate/deep_locate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepMerge/_recursive_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepMerge/cdesc-DeepMerge.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepMerge/deep_merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/DeepMerge/deep_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IgnoreUndeclared/cdesc-IgnoreUndeclared.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IgnoreUndeclared/initialize_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IgnoreUndeclared/property_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/%5b%5d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/cdesc-IndifferentAccess.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/convert%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/convert_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/hash;/cdesc-hash;.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/hash_lacking_indifference%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/hash_with_indifference%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_access%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/indifferent_writer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/inject%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/inject-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/IndifferentAccess/try_convert-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/KeyConversion/cdesc-KeyConversion.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/KeyConversion/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Mash/SafeAssignment/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Mash/SafeAssignment/cdesc-SafeAssignment.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Mash/cdesc-Mash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MergeInitializer/cdesc-MergeInitializer.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MergeInitializer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodAccess/cdesc-MethodAccess.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodAccess/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodAccessWithOverride/cdesc-MethodAccessWithOverride.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodAccessWithOverride/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodOverridingWriter/already_overridden%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodOverridingWriter/cdesc-MethodOverridingWriter.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodOverridingWriter/convert_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodOverridingWriter/method%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodOverridingWriter/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodOverridingWriter/redefine_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodOverridingWriter/respond_to_missing%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodQuery/cdesc-MethodQuery.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodQuery/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodQuery/respond_to%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodReader/cdesc-MethodReader.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodReader/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodReader/respond_to%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodWriter/cdesc-MethodWriter.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodWriter/convert_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodWriter/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/MethodWriter/respond_to%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Parsers/YamlErbParser/cdesc-YamlErbParser.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Parsers/YamlErbParser/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Parsers/YamlErbParser/perform-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Parsers/YamlErbParser/perform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/Parsers/cdesc-Parsers.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/PrettyInspect/cdesc-PrettyInspect.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/PrettyInspect/hashie_inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/PrettyInspect/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/StringifyKeys/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/StringifyKeys/ClassMethods/stringify_keys%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/StringifyKeys/ClassMethods/stringify_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/StringifyKeys/ClassMethods/stringify_keys_recursively%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/StringifyKeys/cdesc-StringifyKeys.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/StringifyKeys/stringify_keys%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/StringifyKeys/stringify_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/SymbolizeKeys/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/SymbolizeKeys/ClassMethods/symbolize_keys%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/SymbolizeKeys/ClassMethods/symbolize_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/SymbolizeKeys/ClassMethods/symbolize_keys_recursively%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/SymbolizeKeys/cdesc-SymbolizeKeys.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/SymbolizeKeys/symbolize_keys%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/SymbolizeKeys/symbolize_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Extensions/cdesc-Extensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Hash/flexibly_convert_to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Hash/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Hash/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Hash/to_mash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/%5b%5d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/assign_property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/cdesc-Mash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/custom_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/deep_merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/deep_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/deep_update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/extractable_options%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/has_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/include%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/initializing_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/member%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/method_suffix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/prefix_method%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/regular_dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/regular_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/respond_to_missing%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/reverse_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/shallow_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/shallow_update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/to_module-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/underbang_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Mash/values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/cdesc-Rash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/optimize_every-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/optimize_if_necessary%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/respond_to_missing%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Rash/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/Trash/cdesc-Trash.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/Hashie/cdesc-Hashie.ri
/usr/lib64/ruby/gems/2.2.0/doc/hashie-3.4.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/UPGRADING.md
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/hashie.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/clash.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/dash.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/coercion.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/dash/indifferent_access.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/dash/property_translation.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_fetch.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_find.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_locate.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_merge.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/ignore_undeclared.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/indifferent_access.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/key_conversion.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/mash/safe_assignment.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/merge_initializer.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/method_access.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/parsers/yaml_erb_parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/pretty_inspect.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/stringify_keys.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/extensions/symbolize_keys.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/mash.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/rash.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/trash.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/lib/hashie/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/clash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/dash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/autoload_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/coercion_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/dash/indifferent_access_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_fetch_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_find_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_locate_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_merge_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/ignore_undeclared_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/indifferent_access_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/indifferent_access_with_rails_hwia_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/key_conversion_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/mash/safe_assignment_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/merge_initializer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/method_access_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/stringify_keys_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/extensions/symbolize_keys_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/hash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/mash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/parsers/yaml_erb_parser_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/rash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/trash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/hashie/version_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/support/module_context.rb
/usr/lib64/ruby/gems/2.2.0/gems/hashie-3.4.2/spec/support/ruby_version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/hashie-3.4.2.gemspec
