#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hashie
Version  : 3.4.2
Release  : 7
URL      : https://rubygems.org/downloads/hashie-3.4.2.gem
Source0  : https://rubygems.org/downloads/hashie-3.4.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core

%description
# Hashie
[![Join the chat at https://gitter.im/intridea/hashie](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/intridea/hashie?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hashie-3.4.2
gem spec %{SOURCE0} -l --ruby > rubygem-hashie.gemspec

%build
gem build rubygem-hashie.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hashie-3.4.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/hashie-3.4.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/UPGRADING.md
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/hashie.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/clash.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/dash.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/coercion.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/dash/indifferent_access.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/dash/property_translation.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_fetch.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_find.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_locate.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/deep_merge.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/ignore_undeclared.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/indifferent_access.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/key_conversion.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/mash/safe_assignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/merge_initializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/method_access.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/parsers/yaml_erb_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/pretty_inspect.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/stringify_keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/extensions/symbolize_keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/mash.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/rash.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/trash.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/lib/hashie/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/clash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/dash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/autoload_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/coercion_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/dash/indifferent_access_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_fetch_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_find_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_locate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/deep_merge_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/ignore_undeclared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/indifferent_access_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/indifferent_access_with_rails_hwia_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/key_conversion_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/mash/safe_assignment_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/merge_initializer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/method_access_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/stringify_keys_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/extensions/symbolize_keys_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/hash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/mash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/parsers/yaml_erb_parser_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/rash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/trash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/hashie/version_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/support/module_context.rb
/usr/lib64/ruby/gems/2.3.0/gems/hashie-3.4.2/spec/support/ruby_version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/hashie-3.4.2.gemspec
